### ISSUE TITLE
Could you possibly provide documentation? 

### ISSUE THREAD

**Issue by punitdarji** [incidrthreat/ctfd-plugin-openvpn#1]
Hi there!
I have seen your and I have installed the given plugin. I would like to request you that please share documation related to setup and how to create a OpenVpn file. Here I have 2 questions, 
1 Is this plugin create vpn tunnel for particular task?
2 Requirements for this plugin

**Comment by incidrthreat** [comment]
@PunitTailor55 I apologize, there is no documentation on this plugin since the plugin is still in paused development.  Installing the plugin will not do anything but show you additional pages.  I stopped developing it bc the requirement that was in place for it, went away.
